// src/App.tsx
import "flowbite";
import "./index.css";

import { MultiProvider } from "@solid-primitives/context";
import { QueryClient, QueryClientProvider } from "@tanstack/solid-query";
import { ParentComponent } from "solid-js";

import Layout from "./components/layout";
import { HostProvider } from "./stores";

const queryClient = new QueryClient({
  defaultOptions: { queries: { refetchOnWindowFocus: false } },
});

const App: ParentComponent = (props) => {
  return (
    <>
      <MultiProvider values={[HostProvider]}>
        <QueryClientProvider client={queryClient}>
          <Layout>{props.children}</Layout>
        </QueryClientProvider>
      </MultiProvider>
    </>
  );
};

export default App;

// src/solidjs/App.tsx
import "flowbite";
import "./index.css";
import "overlayscrollbars/styles/overlayscrollbars.css";

import { MultiProvider } from "@solid-primitives/context";
import { Route, Router } from "@solidjs/router";

import Layout from "./components/layout";
import HostsPage from "./components/pages/hosts-page";
import IdentitiesPage from "./components/pages/identities-page";
import TerminalsPage from "./components/pages/terminals-page";
import { ActiveTerminalProvider, TerminalHistoryProvider } from "./stores";

const App = () => {
  return (
    <>
      <MultiProvider values={[ActiveTerminalProvider, TerminalHistoryProvider]}>
        <Router root={Layout}>
          <Route path="/terminals/:terminalId" component={TerminalsPage} />
          <Route path="/hosts" component={HostsPage} />
          <Route path="/identities" component={IdentitiesPage} />
        </Router>
      </MultiProvider>
    </>
  );
};

export default App;
